# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(verbose_name='\u57ce\u5e02\u53f7')),
                ('name', models.CharField(max_length=10, verbose_name='\u57ce\u5e02\u540d')),
                ('province_id', models.IntegerField(default=0, verbose_name='\u7701\u4efd\u53f7')),
                ('pointx', models.FloatField(verbose_name='\u7ecf\u5ea6')),
                ('pointy', models.FloatField(verbose_name='\u7eac\u5ea6')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='\u57ce\u5e02\u63cf\u8ff0')),
                ('image', models.ImageField(upload_to='city/', verbose_name='logo')),
                ('hot', models.IntegerField(default=0, verbose_name='\u70ed\u95e8\u6307\u6570')),
            ],
        ),
    ]
