# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(default='', upload_to='city/', verbose_name='logo'),
        ),
    ]
