# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20170612_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=30, verbose_name='\u7701\u4efd\u540d')),
                ('wm', models.CharField(max_length=5, verbose_name='\u7701\u4efd\u540d\u7f29\u5199')),
            ],
        ),
    ]
